var model = {
        "Christa": {
            aMaiden: "",
            aMerry: "",
            aveMariaElgar: "Alto",
            aveVerumByrd: "Alto",
            bringTorch: "Alto",
            cantate: "Alto",
            downToTheRiver: "--",
            egoSumPanis: "Alto",
            gabriel: "",
            gottIst: "Alto 1",
            heWatching: "Alto",
            heIsBorn: "",
            hodie: "Alto",
            howLovely: "Alto",
  infant: "Alto",
            isItFar: "Alto",
            jesuJoy: "Alto",
            jesusChild: "--",
            locusIste: "Alto",
            magnificat: "Alto 1",
            oQuam: "Alto",
            oRexGloriae: "--",
            puerNatus: "Alto 1",
            thouWilt: "Alto",
  verbumCaro: "Alto",
            whatChild: "",
  whenJesus: ""
          },
          "Christian": {
            aMaiden: "v. 4 Baritone",
            aMerry: "Bass",
            aveVerumByrd: "Bass",
            aveMariaElgar: "Tenor",
            bringTorch: "",
            cantate: "Bass",
            downToTheRiver: "",
            egoSumPanis: "Tenor",
            gabriel: "",
            gottIst: "--",
            heWatching: "Bass",
            heIsBorn: "B1 &amp; T2",
            hodie: "Bass",
            howLovely: "Bass",
  infant: "Bass",
            isItFar: "Bass",
            jesuJoy: "Tenor",
            jesusChild: "Baritone",
            locusIste: "Bass",
            oQuam: "Bass",
            oRexGloriae: "Baritone",
            magnificat: "Tenor<\/br>m.46 solo",
            puerNatus: "v.1-4 Bass<\/br>v.5 Tenor 2",
            thouWilt: "Tenor 2",
  verbumCaro: "Tenor 2",
            whatChild: "divisi: Baritone",
  whenJesus: "pt.2 Baritone"
          },
          "David": {
            aMaiden: "",
            aMerry: "Tenor",
            aveMariaElgar: "Tenor",
            aveVerumByrd: "Tenor",
            bringTorch: "",
            cantate: "Tenor",
            downToTheRiver: "--",
            egoSumPanis: "Tenor",
            gabriel: "",
            gottIst: "--",
            heWatching: "Tenor",
            heIsBorn: "Tenor 1",
            hodie: "Tenor",
            howLovely: "Tenor",
  infant: "Tenor",
            isItFar: "Tenor",
            jesuJoy: "Tenor",
            jesusChild: "--",
            locusIste: "Tenor",
            magnificat: "Tenor",
            oQuam: "Tenor",
            oRexGloriae: "--",
            puerNatus: "Tenor 1",
            thouWilt: "Tenor 1",
  verbumCaro: "Tenor 2",
            whatChild: "Tenor",
  whenJesus: "pt. 2 Tenor"
          },
          "Debbie": {
            aMaiden: "",
            aMerry: "",
            aveMariaElgar: "Soprano",
            aveVerumByrd: "Soprano",
            bringTorch: "Soprano",
            cantate: "Soprano 1",
            downToTheRiver: "",
            egoSumPanis: "Soprano",
            gabriel: "",
            gottIst: "Soprano 1",
            heWatching: "Soprano",
            heIsBorn: "",
            hodie: "Cantus",
            howLovely: "Soprano",
  infant: "Soprano",
            isItFar: "Soprano 1",
            jesuJoy: "Soprano",
            jesusChild: "Soprano",
            locusIste: "Soprano",
            magnificat: "Soprano<\/br>mm.26, 49 solo",
            oQuam: "Soprano",
            oRexGloriae: "Soprano",
            puerNatus: "Soprano 1<\/br>Holding F",
            thouWilt: "Soprano",
  verbumCaro: "Soprano",
            whatChild: "Soprano",
  whenJesus: ""
          },

          "Esther": {
            aMaiden: "Alto 2",
            aMerry: "",
            aveMariaElgar: "",
            aveVerumByrd: "",
            bringTorch: "",
            cantate: "",
            downToTheRiver: "",
            egoSumPanis: "",
            gabriel: "",
            gottIst: "",
            heWatching: "",
            heIsBorn: "",
            hodie: "",
            howLovely: "",
  infant: "Alto",
            isItFar: "",
            jesuJoy: "",
            jesusChild: "--",
            locusIste: "",
            magnificat: "",
            oQuam: "",
            oRexGloriae: "",
            puerNatus: "",
            thouWilt: "",
  verbumCaro: "Alto",
            whatChild: "",
  whenJesus: "pt. 1 solo"
          },

          "George": {
            aMaiden: "",
            aMerry: "Bass",
            aveMariaElgar: "Bass",
            aveVerumByrd: "Bass",
            bringTorch: "",
            cantate: "Bass",
            downToTheRiver: "--",
            egoSumPanis: "Bass",
            gabriel: "",
            gottIst: "--",
            heWatching: "Bass",
            heIsBorn: "Bass 2",
            hodie: "Bass",
            howLovely: "Bass",
  infant: "Bass",
            isItFar: "Bass",
            jesuJoy: "Bass",
            jesusChild: "--",
            locusIste: "Bass",
            magnificat: "Bass",
            oQuam: "Bass",
            oRexGloriae: "--",
            puerNatus: "Bass 2",
            thouWilt: "Bass 2",
  verbumCaro: "Bass",
            whatChild: "Bass",
  whenJesus: "pt. 2 Bass"
          },
          "Joy": {
            aMaiden: "",
            aMerry: "",
            aveMariaElgar: "Alto",
            aveVerumByrd: "Alto",
            bringTorch: "Alto",
            cantate: "Alto",
            downToTheRiver: "",
            egoSumPanis: "Alto",
            gabriel: "",
            gottIst: "Alto 2",
            heWatching: "Alto",
            heIsBorn: "",
            hodie: "Alto",
            howLovely: "Alto",
  infant: "Bass",
            isItFar: "Alto",
            jesuJoy: "Alto",
            jesusChild: "Alto",
            locusIste: "Alto",
            magnificat: "Alto 2<\/br>mm.2, 71 solo",
            oQuam: "Alto",
            oRexGloriae: "Alto",
            puerNatus: "Alto 2",
            thouWilt: "Alto",
  verbumCaro: "Alto",
            whatChild: "",
  whenJesus: ""
          },

          "Julio": {
            aMaiden: "",
            aMerry: "",
            aveMariaElgar: "",
            aveVerumByrd: "",
            bringTorch: "",
            cantate: "",
            downToTheRiver: "",
            egoSumPanis: "",
            gabriel: "",
            gottIst: "",
            heWatching: "",
            heIsBorn: "Bass 2",
            hodie: "",
            howLovely: "",
  infant: "Bass",
            isItFar: "",
            jesuJoy: "",
            jesusChild: "--",
            locusIste: "",
            magnificat: "",
            oQuam: "",
            oRexGloriae: "",
            puerNatus: "",
            thouWilt: "",
  verbumCaro: "Bass",
            whatChild: "Bass<\/br>Solo v. 1",
  whenJesus: "pt. 2 Bass"
          },

          "Larry": {
            aMaiden: "",
            aMerry: "Bass",
            aveMariaElgar: "Bass",
            aveVerumByrd: "Bass",
            bringTorch: "",
            cantate: "Bass",
            downToTheRiver: "",
            egoSumPanis: "Bass",
            gabriel: "",
            gottIst: "--",
            heWatching: "Bass",
            heIsBorn: "Bass 1",
            hodie: "Bass",
            howLovely: "Bass",
  infant: "Bass<br>v.3 solo",
            isItFar: "Bass",
            jesuJoy: "Bass",
            jesusChild: "Bass",
            locusIste: "Bass",
            magnificat: "Bass<\/br>mm.24, 56 solo",
            oQuam: "Bass",
            oRexGloriae: "Bass",
            puerNatus: "Bass 1",
            thouWilt: "Bass 1",
  verbumCaro: "Bass",
            whatChild: "Baritone",
  whenJesus: "pt. 2 Baritone"
          },
          "Mary": {
            aMaiden: "Soprano",
            aMerry: "Soprano",
            aveMariaElgar: "",
            aveVerumByrd: "Soprano",
            bringTorch: "Soprano<\/br>Middle note on divisi",
            cantate: "Soprano 2",
            downToTheRiver: "--",
            egoSumPanis: "",
            gabriel: "v. 3 Solo",
            gottIst: "Soprano 2",
            heWatching: "Alto",
            hodie: "Quintus",
            howLovely: "Soprano",
  infant: "Soprano",
            isItFar: "Soprano 2",
            jesuJoy: "",
            jesusChild: "--",
            locusIste: "",
            magnificat: "Alto 1<\/br>mm. 27, 72 solo",
            oQuam: "",
            oRexGloriae: "--",
            puerNatus: "Alto 1",
            thouWilt: "Soprano",
  verbumCaro: "Soprano 1",
            whatChild: "Alto<br>middle note on divisi",
  whenJesus: "Soprano"
          },
          "Michael": {
            aMaiden: "",
            aMerry: "Tenor",
            aveMariaElgar: "Tenor",
            aveVerumByrd: "Tenor",
            bringTorch: "",
            cantate: "Tenor",
            downToTheRiver: "",
            egoSumPanis: "Tenor",
            gabriel: "",
            gottIst: "--",
            heWatching: "Tenor",
            heIsBorn: "Tenor 1",
            hodie: "Tenor",
            howLovely: "Tenor",
  infant: "Tenor",
            isItFar: "Tenor",
            jesuJoy: "Tenor",
            jesusChild: "Tenor",
            locusIste: "Tenor",
            magnificat: "Tenor",
            oQuam: "Tenor",
            oRexGloriae: "",
            puerNatus: "Tenor 1",
            thouWilt: "Tenor 1",
  verbumCaro: "Tenor 1",
            whatChild: "Tenor",
  whenJesus: "pt. 2 Tenor"
          },
          "Pat": {
            aMaiden: "Soprano",
            aMerry: "Soprano",
            aveMariaElgar: "Soprano",
            aveVerumByrd: "Soprano",
            bringTorch: "Soprano",
            cantate: "Soprano 2",
            downToTheRiver: "--",
            egoSumPanis: "Soprano",
            gabriel: "Soprano",
            gottIst: "Alto 1",
            heWatching: "Soprano",
            heIsBorn: "Soprano",
            hodie: "Quintus",
            howLovely: "Soprano",
  infant: "Soprano<br>v.1 solo",
            isItFar: "Soprano 1",
            jesuJoy: "Soprano",
            jesusChild: "--",
            locusIste: "Soprano",
            magnificat: "Soprano",
            oQuam: "Soprano",
            oRexGloriae: "--",
            puerNatus: "Soprano 2<\/br>Holding C",
            thouWilt: "Soprano",
  verbumCaro: "Soprano 2",
            whatChild: "Soprano 1",
  whenJesus: "Soprano"
          },
          "Name...": {
            aMaiden: "",
            aMerry: "",
            aveMariaElgar: "",
            aveVerumByrd: "",
            bringTorch: "",
            cantate: "",
            downToTheRiver: "",
            egoSumPanis: "",
            gabriel: "",
            gottIst: "",
            heWatching: "",
            heIsBorn: "",
            hodie: "",
            howLovely: "",
  infant: "",
            isItFar: "",
            jesuJoy: "",
            jesusChild: "",
            locusIste: "",
            magnificat: "",
            oQuam: "",
            oRexGloriae: "",
            puerNatus: "",
            thouWilt: "",
  verbumCaro: "",
            whatChild: "",
  whenJesus: ""
          }
        };

        // Populates the voice list using data above
        function changeWords() {
          var t = model[document.getElementById("voiceNames").value];

          for (var x in t) {
            console.log(x);
            document.getElementById(x).innerHTML = t[x];
          }
        }
        document.getElementById("voiceNames").onchange = changeWords;

        // End voice list -->

        
